name: "web_app"
mode: "dev"
port: 8081
version: "v1.0.0"

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root"
  dbname: "sql_demo"
  max_conns: 200
  max_idle_conns: 50
redis:
  host: "127.0.0.1"
  port: 16379
  db: 0
  password: ""
  pool_size: 0
